Added tintColor for android
cooperka/react-native-snackbar pull request #9
Opened 2016-12-23 06:11 UTC by iRoachie

Adds tintColor param for android. Currently only uses hex values. By default tintColor is white if no tintColor is explicitly set (Fixes #6)

2016-12-23 16:39 UTC, cooperka commented
Thanks @iRoachie! Code logic LGTM, I'll test it out soon before merging.

2016-12-23 16:44 UTC, cooperka requested changes

2016-12-23 16:44 UTC, cooperka commented on index.js
> +     if(!options.tintColor) {
Could we call this `textColor` instead? And it should probably also be added to the docs.

2016-12-23 16:59 UTC, iRoachie commented on index.js
> +     if(!options.tintColor) {
Oh I just called it tintColor cause that's what it's called on all the other react native components.

2016-12-23 22:02 UTC, cooperka commented on index.js
> +     if(!options.tintColor) {
I'm not sure which components you're referring to, but I think generally tint is used for images (not text). Android also uses textColor to specify this on their [native snackbars](https://developer.android.com/reference/android/support/design/widget/Snackbar.html).

2016-12-24 08:01 UTC, iRoachie commented on index.js
> +     if(!options.tintColor) {
Alright will make the change

2016-12-24 08:19 UTC, iRoachie reviewed
Changes added. Also documented

2016-12-29 23:22 UTC, cooperka commented
@iRoachie I tested it out and it turns out there's a [better fix](https://github.com/cooperka/react-native-snackbar/commit/85b089045f4647876732680837b02c0e062edd9f) that I've implemented already. This PR is still valid though -- I think it would be great to be able to set textColor, unrelated to #6. I'll rebase this on the latest master soon and merge. Thanks again for your help!

2016-12-30 10:56 UTC, iRoachie commented
Alright then great! I'll cancel this one and come up with another way of setting textColor using the method you used. Thanks

2016-12-30 13:03 UTC, cooperka commented
You could even keep this PR open if you prefer, since the title is still accurate and the code is pretty much the same! I was thinking instead of hardcoding `snackbarText.setTextColor(Color.WHITE);` we could just pass in the color that the user specified. Should hopefully be pretty straightforward.

2016-12-30 13:07 UTC, iRoachie commented
We would need someway to map colours (rgb, solids, hex) to the respect android IOS Color classes

2017-01-17 13:03 UTC, closed without merging