Added feature to position snackbar on the screen (Android)
cooperka/react-native-snackbar pull request #91
Opened 2018-10-07 18:21 UTC by imMayankRaj

Plus working on #70

2018-10-07 21:02 UTC, cooperka requested changes
Just a few nits for consistency 😸 looks good overall!

2018-10-07 21:02 UTC, cooperka commented on src/index.js
> +    console.log(options);
Please remove log

2018-10-07 21:02 UTC, cooperka commented on src/index.js
> +  gravity?:number,
Space after colon

2018-10-07 21:02 UTC, cooperka commented on src/index.d.ts
> +  gravity?:number;
- Put comment directly above property (no extra newline)
- Add newline below property
- Add space after colon

2018-10-07 21:02 UTC, cooperka commented on android/src/main/java/com/azendoo/reactnativesnackbar/SnackbarModule.java
> +        if(options.hasKey("gravity")) {
Space after `if`

2018-10-07 21:02 UTC, cooperka commented on android/src/main/java/com/azendoo/reactnativesnackbar/SnackbarModule.java
> +            FrameLayout.LayoutParams params =(FrameLayout.LayoutParams)snackbarView.getLayoutParams();
Space after `=`

2018-10-07 21:07 UTC, cooperka commented
Hi @imMayankRaj, thanks for this. Does the animation look good when it's at the top? In other words, does the snackbar slide down instead of up when you position it at the top? If so I'd be happy merging on 2 conditions:

1. Please update README to document new props
2. File a ticket to add this prop to iOS as well. You don't have to do it yourself, this is more of a note to myself.

2018-10-08 13:34 UTC, imMayankRaj commented
Changing the gravity of the Snackbar has no effect on the animation. It's still the same.

2018-10-08 15:19 UTC, cooperka commented
Hmm, doesn't that look quite strange? I think we'll need to find a different solution in that case. Thoughts?

2018-10-08 15:55 UTC, imMayankRaj commented
Sorry, my bad, it's working as expected i.e it's sliding down when at the bottom and sliding up when at the top. And also the view gets dismissed as a whole i.e without any sliding animation, when at the center.

2018-10-08 17:10 UTC, closed without merging

2018-10-08 17:16 UTC, cooperka commented
I tried to push updated code to your branch and GitHub seems to have reacted by closing this PR automatically. I'm unable to re-open. Can you please do this on your machine:

```console
cd react-native-snackbar/
git push origin 9428680:master -f
```

That will restore your latest commit back to your branch. Apologies for the inconvenience; hopefully that allows me to re-open the PR.

2018-10-08 17:23 UTC, cooperka commented
I also tested it on my emulator and the animation isn't behaving as expected. Can you post a screen recording and some info about your device version? I'm expecting the Snackbar to slide in and out from the top as you described.

Here's what I see, no change in animation when positioned at the top:

![animation of snackbar with gravity](https://user-images.githubusercontent.com/2047062/46623910-30db1180-cafd-11e8-9ce4-0cfdbfcbfe0f.gif)

2018-10-08 21:01 UTC, imMayankRaj commented
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25002339/46633260-ceb8f580-cb6a-11e8-8eb5-53eca730ae28.gif)

It's working fine on my device.
I am using a physical device.
MOTO g5 plus
Android 8.1

2018-10-08 21:01 UTC, imMayankRaj commented
> 
> 
> I tried to push updated code to your branch and GitHub seems to have reacted by closing this PR automatically. I'm unable to re-open. Can you please do this on your machine:
> 
> ```
> cd react-native-snackbar/
> git push origin 9428680:master -f
> ```
> 
> That will restore your latest commit back to your branch. Apologies for the inconvenience; hopefully that allows me to re-open the PR.

Done. Try again

2018-10-09 02:38 UTC, cooperka commented
> Try again

No luck :crying_cat_face: I've never encountered this before. I can always merge manually later on.

> It's working fine on my device

The animations don't seem to be coming through from your screen recorder. I just see it flash onto the screen with no animation.

2018-10-09 05:42 UTC, imMayankRaj commented
No, it's working as taken by recorder. That was the reason I was confused. The animation doesn't come up, on my device, as you are expecting.

2018-10-09 17:30 UTC, cooperka commented
Strange! I wonder if your animations are disabled somehow. Unfortunately I won't be able to merge this PR until the animation happens properly... I'm not sure if Snackbar would support that easily or not.